### ISSUE TITLE
BBF_Ombi

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#11]
can we remove the this line?
![image](https://user-images.githubusercontent.com/6140137/48641511-a27d6980-e99f-11e8-9bd4-d383d97f113b.png)

it bothers the ever loving out of me.
![image](https://user-images.githubusercontent.com/6140137/48641558-c3de5580-e99f-11e8-9cb5-f654ab35bf33.png)

**Comment by Archmonger** [comment]
Dotted line in the settings menu has been removed.
