### ISSUE TITLE
Left Nav icons floating through the NAVIGATION text

### ISSUE THREAD

**Issue by kdoubledubs** [Archmonger/Blackberry-Themes#13]
Tab Icons are floating through the NAVIGATION text on left. Using on top of burry.
<img width="589" alt="screen shot 2018-12-08 at 9 20 40 am" src="https://user-images.githubusercontent.com/16267805/49691575-d3bb0680-fb13-11e8-85dc-592fb30708e0.png">

**Comment by Archmonger** [comment]
Known issue reported by goldenpipes. A JavaScript solution is needed due to the way that CauseFX structured the HTML of the sidenav. Will eventually get to fixing it.

**Comment by Archmonger** [comment]
Figured out a CSS workaround to fix this issue. Has been pushed to `bbf_organizr_on_top_of_burry.css`.
