### ISSUE TITLE
Close X button needs styling in Org Plugin popup windows

### ISSUE THREAD

**Issue by kdoubledubs** [Archmonger/Blackberry-Themes#14]
<img width="1254" alt="screen shot 2018-12-08 at 6 09 07 pm" src="https://user-images.githubusercontent.com/16267805/49691614-825f4700-fb14-11e8-81ef-89a204985d04.png">

**Comment by Archmonger** [comment]
bff organizr, or organizr on top of burry?

**Comment by kdoubledubs** [comment]
on top of burry

**Comment by Archmonger** [comment]
What browser?

**Comment by Archmonger** [comment]
Also, does the issue persist with the BBF on top of burry theme removed?

**Comment by kdoubledubs** [comment]
Chrome.  It does persist.  Same deal as the other issue.  This is a burry issue.  My bad.

**Comment by Archmonger** [comment]
https://github.com/Burry/organizr-v2-plex-theme
Let burry know! If he doesn't fix it within a reasonable time frame I'll use `on top of burry` to fix it.
