### ISSUE TITLE
Tab Editor window "?" link needs styling

### ISSUE THREAD

**Issue by kdoubledubs** [Archmonger/Blackberry-Themes#15]
<img width="1259" alt="screen shot 2018-12-08 at 6 08 23 pm" src="https://user-images.githubusercontent.com/16267805/49691616-99059e00-fb14-11e8-91e2-4385e600da1b.png">

on top of burry

**Comment by Archmonger** [comment]
Does this issue persist without the on top of burry theme applied?

**Comment by kdoubledubs** [comment]
Yes it does.  So its a burry issue.  :)

**Comment by Archmonger** [comment]
https://github.com/Burry/organizr-v2-plex-theme 
Let burry know! If he doesn't fix it within a reasonable time frame I'll use `on top of burry` to fix it.
