### ISSUE TITLE
Quality profile selector button

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#18]
is on the same line as root folder which pushes it off the card.

![image](https://user-images.githubusercontent.com/6140137/50938875-d6c15380-143f-11e9-885e-56a50ca1521a.png)

**Comment by Archmonger** [comment]
Can't seem to get this to occur on my build. I attempted a fix, let me know if it works.

**Comment by goldenpipes** [comment]
hmm this is strange i wonder if its a resolution issue. let me check some stuff

**Comment by goldenpipes** [comment]
think i found out whats happening.

if i uncheck that checkbox it behaves normally. but idk if its gonna break anything else.

![2019-01-10_18-41-33](https://user-images.githubusercontent.com/6140137/51006121-62ea7e00-1507-11e9-845e-18db0918251d.gif)

not sure why though.  It happens if im in organizr or not. no other css is being applied to ombi.

the window size it happnens on is 1200 pixels wide. no friggen idea,

**Comment by Archmonger** [comment]
What browser and ombi build #?
Also does this occur with BFF removed?

**Comment by goldenpipes** [comment]
Chrome. Latest dev and latest Master. It doesn't do it with bbf disabled.

**Comment by Archmonger** [comment]
New attempted fix was pushed, let me know if it's resolved.

**Comment by goldenpipes** [comment]
that did it!
