### ISSUE TITLE
Flood Plex theme 

### ISSUE THREAD

**Issue by stefanelul2000** [Archmonger/Blackberry-Themes#2]
I'd like to have the plex theme for the flood interface.

**Comment by goldenpipes** [comment]
What's the flood interface?

**Comment by stefanelul2000** [comment]
It's a Web Interface for rTorrent.

**Comment by stefanelul2000** [comment]
As I can no longer get flood to work with rtorrent I no longer find any reason for me to request a theme for it.

**Comment by Archmonger** [comment]
If you change your mind, you can upvote the theme on Feathub.
