### ISSUE TITLE
Tautulli theme - Notification bell icon same color for active/inactive triggers

### ISSUE THREAD

**Issue by mcleodd10** [Archmonger/Blackberry-Themes#20]
In Tautulli, there's a bell icon next to configured notification agents and it's either yellow or grayed out to indicate whether there are triggers active. When the theme is active there's no differing color to indicate that an agent is active, so you can't really tell at a glance.

Also, since Feathub is currently down, has a theme/organizr icon for NzbHydra been suggested? Cheers.

**Comment by Archmonger** [comment]
Thanks for letting me know about this bug. I have released a fix, clear cache and it should be good.
I don't believe NzbHydra has received a vote on feathub for either a theme or icon, but I don't quite have the feathub lists memorized so I can't confirm until it comes back up.
