### ISSUE TITLE
BBF Organizr on top of Burry needs styling for news section

### ISSUE THREAD

**Issue by rg9400** [Archmonger/Blackberry-Themes#25]
The just-added news section needs some styling

![image](https://user-images.githubusercontent.com/39887349/53608027-cb102480-3b86-11e9-9b89-7752a5d13d0d.png)

**Comment by Archmonger** [comment]
Thanks for letting me know. I will get to this upon restructuring BBF Organizr. Current plan is to make a complete fork burry's theme since he hasn't been maintaining it.

**Comment by Archmonger** [comment]
BBF Organizr is now a fork of burry. This issue has been fixed in the latest version
