### ISSUE TITLE
BBF Plex Media Modal has extra scrollbar

### ISSUE THREAD

**Issue by rg9400** [Archmonger/Blackberry-Themes#28]
![image](https://user-images.githubusercontent.com/39887349/54476418-1fdcad80-47cb-11e9-8ec3-eb988e389367.png)

The scrollbar furthest to the right

Plex Web version 3.83.1

**Comment by Archmonger** [comment]
Can you confirm this doesn't happen with BBF turned off?

**Comment by rg9400** [comment]
Confirmed, it is only with BBF on (I use the _in_organizr variant)

![image](https://user-images.githubusercontent.com/39887349/54478797-1c095500-47e4-11e9-8115-4a17d0ccacd5.png)
