### ISSUE TITLE
[Feature Request] Theme Park Glass Login Addon

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Archmonger/Blackberry-Themes#40]
Any way to get Theme Park Glass login addon to work with Organizr minimal edition (Blackberry Shadow)? 
https://github.com/gilbN/theme.park/tree/master/CSS/addons/organizr/glass#login---lockscreen

I tried to put 

`@import "https://gilbn.github.io/theme.park/CSS/addons/organizr/glass/glass-login.css";
:root {
    --div-background-color-10: rgba(255, 255, 255, 0.10);
    --div-background-color-15: rgba(255, 255, 255, 0.15);
    --div-background-color-25: rgba(255, 255, 255, 0.25);
    --div-background-color-35: rgba(255, 255, 255, 0.35);
}`

in "Custom CSS" box with Blackberry minimal edition (Blackberry Shadow) but Blackberry Themes seems to override it and looks funky.

**Comment by Archmonger** [comment]
Not possible due to wildly different code that me and GilbN use to theme. A Glass extra for Blackberry Themes is planned, but has no ETA.
