### ISSUE TITLE
Theme Installer/remplacer

### ISSUE THREAD

**Issue by Nosirus** [Archmonger/Blackberry-Themes#46]
does it work directly in organizr V2 without using a reverse proxy ? with the ip of the service.

**Comment by Archmonger** [comment]
Unfortunately, around the beginning of 2020 all major browsers have implemented security changes. These new security changes prevent the Theme Installer from working on LAN. I have not been able to determine a work around.

So unfortunately, now a reverse proxy is required for theme installer to work.
