### ISSUE TITLE
[Request] New Icons

### ISSUE THREAD

**Issue by rg9400** [Archmonger/Blackberry-Themes#47]
I know you're busy, but would appreciate new icons (BBF theme is the one I use) for below apps

1. Readarr - https://github.com/Readarr/Readarr/blob/develop/Logo/Readarr.svg
2. GAPS - https://github.com/JasonHHouse/gaps/blob/master/images/Final-Black.png or https://github.com/JasonHHouse/gaps/blob/master/images/gaps.png
3. XBVR - https://github.com/xbapps/xbvr/blob/master/ui/public/icons/xbvr-512.png or https://iconify.design/icon-sets/fa-solid/vr-cardboard.html
4. Stash - I couldn't find an official icon for this one, but here's the repo (NSFW) https://github.com/stashapp/stash

**Comment by Archmonger** [comment]
I got you.
