### ISSUE TITLE
[Feature Request] New icons for Calibre Web/Calibre Content Server

### ISSUE THREAD

**Issue by rg9400** [Archmonger/Blackberry-Themes#49]
**Theme File** 
Blackberry Flat

Sorry to ask for more icons, but I noticed you have one BBF icon for Calibre. I also run Calibre-Web and Calibre's content server, could you possibly create a few more variants of the book icon?

**Comment by Archmonger** [comment]
I should be thanking you for requesting icons! I wouldn't know they needed to exist if they didn't get requested!
