### ISSUE TITLE
WINDOWS | Can not use subfilter for Deluge

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#7]
Deluge has an issue where it won't pass all of the files through the reverse proxy for some reason.
This seems to only affect Windows.

A workaround is to just add all of the code to the end of `deluge.css` located in:

`%Program Files (x86)%\Deluge\deluge-1.3.15-py2.7.egg\deluge\ui\web\css`

I figured other users may come across this issue trying to do a reverse proxy for Deluge on Windows in general.

Maybe just add this to install instructions?

**Comment by Archmonger** [comment]
Added to readme.md
